name: weather_app_riverpod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.2
  cloud_functions: ^4.6.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  intl: ^0.18.1
  logger: ^2.0.2
  multiple_result: ^5.1.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf

  assets:
    - assets/weather_icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: false
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: false
    image_path: "assets/logo.png"
